// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsryxjnaalewxicsvnst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcnl4am5hYWxld3hpY3N2bnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDI3NTQsImV4cCI6MjA2NzM3ODc1NH0.yLMxNK-NwjXuEjEoyINKSEauD1rc86kNl92hSVcFmak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});